# Create a symlink to home directory.
# ln -s ~/repos/dotfiles/.Brewfile ~/.Brewfile

tap "homebrew/bundle"
tap "homebrew/services"
brew "ffmpeg"
brew "fnm"
brew "git"
brew "gnupg"
brew "k9s"
brew "kubectx"
brew "kubeseal"
brew "kustomize"
brew "node"
brew "poetry"
brew "postgis"
brew "postgresql"
brew "pyenv"
brew "vips"
brew "wget"
brew "yarn"
cask "appcleaner"
cask "cyberduck"
cask "discord"
cask "iterm2"
cask "microsoft-teams"
cask "ngrok"
cask "notunes"
cask "omnidisksweeper"
cask "postico"
cask "rectangle"
cask "slack"
cask "spotify"
cask "visual-studio-code"
