tap "homebrew/bundle"
tap "homebrew/services"

brew "git"
brew "gnupg"
brew "k9s"
brew "kubectx"
brew "kubeseal"
brew "kustomize"
brew "node"
brew "poetry"
brew "postgresql"
brew "pyenv"
brew "wget"
brew "yarn"
brew "nvm"
brew "docker-compose"

cask "appcleaner"
cask "cyberduck"
cask "discord"
cask "docker"
cask "iterm2"
cask "ngrok"
cask "omnidisksweeper"
cask "postico"
cask "rectangle"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "microsoft-teams"
cask "notunes"

