"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[line_break]
disabled = true

[kubernetes]
disabled = false
symbol =  '☸️ '
format = '[$namespace $symbol]($style)'

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[➜](bold red) '

[python]
format = '[($symbol$virtualenv )]($style)'

[nodejs]
disabled = true

[pixi]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
format = '([$all_status$ahead_behind]($style) )'
stashed = ''
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[cmd_duration]
disabled = true

[package]
disabled = true
