"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[line_break]
disabled = true

[kubernetes]
disabled = false
format = '[$namespace $symbol]($style)'

[[kubernetes.contexts]]
context_pattern = 'ras.histify.net-hf-k8s-prod'
style = 'bold red'
symbol = '⛈️ 🔴 '

[[kubernetes.contexts]]
context_pattern = 'ras.histify.net-hf-k8s-test'
style = 'bold yellow'
symbol = '⛅️ 🟡 '

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[➜](bold red) '

[python]
symbol = '🐍'
format = '[$symbol]($style) '
detect_extensions = []
detect_files = []
detect_folders = []
detect_env_vars = ['VIRTUAL_ENV']

[nodejs]
disabled = true

[pixi]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
format = '([$all_status$ahead_behind]($style) )'
stashed = ''
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[cmd_duration]
disabled = true

[package]
disabled = true

[docker_context]
disabled = true
